# Generated by Django 3.1.3 on 2020-11-22 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201121_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_student',
        ),
        migrations.AlterField(
            model_name='account',
            name='function',
            field=models.CharField(choices=[('Student', 'Student'), ('Professor', 'Professor')], default='Student', max_length=20, verbose_name='Function'),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
